[package]
name = "fuscum"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
ast-grep-core = "0.40.0"
ast-grep-language = "0.39.7"
typed-builder = "0.23.0"

[dev-dependencies]
insta = "1.41.1"